### ISSUE TITLE
Illegal characters in filenames

### ISSUE THREAD

**Issue by marvin-burmeister** [regendo/guild-wars-skill-cards#2]
Hey, I wanted to try out your tool but it fails at the very first skill icon.

```
Running `target\debug\guild-wars-skill-cards.exe`
thread 'main' panicked at 'Couldn't write to cache/images/"Charge!".jpg.: Os { code: 123, kind: Other, message: "Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch." }', src\io.rs:134:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\guild-wars-skill-cards.exe` (exit code: 101)
```

I guess windows 10 doesn't like the " characters in filenames. Any ideas why it fails for me?

**Comment by EmilyMalkieri** [comment]
Thanks Marvin!

I keep forgetting that just because I run the program on my windows computer, it doesn't necessarily "run on windows". Windows indeed doesn't allow `"` in file names but apparently WSL does, that's why this didn't happen to me last time I tried it.

I'll push a fix in a moment.
